package com.zp.smaple;

/**
 * Created by zengpu on 2016/11/25.
 */

public class StringContentUtil {

    public static String str_hanzi = "<p>　　壬戌之秋，七月既望，苏子与客泛舟游于赤壁之下。清风徐来，水波不兴。举酒属客，诵明月之诗，歌窈窕之章。少焉，月出于东山之上，徘徊于斗牛之间。白露横江，水光接天。纵一苇之所如，凌万顷之茫然。浩浩乎如冯虚御风，而不知其所止；飘飘乎如遗世独立,羽化而登仙。︵冯 通：凭︶</p> <p>　　于是饮酒乐甚，扣舷而歌之。歌曰：﹃桂棹兮兰桨，击空明兮溯流光。渺渺兮予怀，望美人兮天一方。﹄客有吹洞箫者，倚歌而和之。其声呜呜然，如怨如慕，如泣如诉；余音袅袅，不绝如缕。舞幽壑之潜蛟，泣孤舟之嫠妇。</p> <p>　　苏子愀然，正襟危坐，而问客曰：﹃何为其然也？﹄客曰：﹃﹁月明星稀，乌鹊南飞。﹂此非曹孟德之诗乎？西望夏口，东望武昌，山川相缪，郁乎苍苍，此非孟德之困于周郎者乎？方其破荆州，下江陵，顺流而东也，舳舻千里，旌旗蔽空，酾酒临江，横槊赋诗，固一世之雄也，而今安在哉？况吾与子渔樵于江渚之上，侣鱼虾而友麋鹿，驾一叶之扁舟，举匏樽以相属。寄蜉蝣于天地，渺沧海之一粟。哀吾生之须臾，羡长 江之无穷。挟飞仙以遨游，抱明月而长终。知不可乎骤得，托遗响于悲风。﹄</p> <p>　　苏子曰：﹃客亦知夫水与月乎？逝者如斯，而未尝往也；盈虚者如彼，而卒莫消长也。盖将自其变者而观之，则天地曾不能以一瞬；自其不变者而观之，则物与我皆无尽也，而又何羡乎！且夫天地之间，物各有主，苟非吾之所有，虽一毫而莫取。惟江上之清风，与山间之明月，耳得之而为声，目遇之而成色，取之无禁，用之不竭。是造物者之无尽藏也，而吾与子之所共适。﹄︵共适 一作：共食︶</p> <p>　　客喜而笑，洗盏更酌。肴核既尽，杯盘狼籍。相与枕藉乎舟中，不知东方之既白。</p>";
    public static String str_cbf = "<p>　　壬戌之秋，七月既望，蘇子與客泛舟遊於赤壁之下。清風徐來，水波不興。舉酒屬客，誦明月之詩，歌窈窕之章。少焉，月出於東山之上，徘徊於鬥牛之間。白露橫江，水光接天。縱壹葦之所如，淩萬頃之茫然。浩浩乎如馮虛禦風，而不知其所止；飄飄乎如遺世獨立,羽化而登仙。︵馮 通：憑︶</p> <p>　　於是飲酒樂甚，扣舷而歌之。歌曰：﹃桂桌兮蘭槳，擊空明兮溯流光。渺渺兮予懷，望美人兮天壹方。﹄客有吹洞簫者，倚歌而和之。其聲嗚嗚然，如怨如慕，如泣如訴；余音裊裊，不絕如縷。舞幽壑之潛蛟，泣孤舟之嫠婦。</p> <p>　　蘇子愀然，正襟危坐，而問客曰：﹃何為其然也？﹄客曰：﹃﹁月明星稀，烏鵲南飛。﹂此非曹孟德之詩乎？西望夏口，東望武昌，山川相繆，郁乎蒼蒼，此非孟德之困於周郎者乎？方其破荊州，下江陵，順流而東也，舳艫千裏，旌旗蔽空，釃酒臨江，橫槊賦詩，固壹世之雄也，而今安在哉？況吾與子漁樵於江諸之上，侶魚蝦而友麋鹿，駕壹葉之扁舟，舉匏樽以相屬。寄蜉蝣於天地，渺滄海之壹粟。哀吾生之須臾，羨長 江之無窮。挾飛仙以遨遊，抱明月而長終。知不可乎驟得，托遺響於悲風。﹄</p> <p>　　蘇子曰：﹃客亦知夫水與月乎？逝者如斯，而未嘗往也；盈虛者如彼，而卒莫消長也。蓋將自其變者而觀之，則天地曾不能以壹瞬；自其不變者而觀之，則物與我皆無盡也，而又何羨乎！且夫天地之間，物各有主，茍非吾之所有，雖壹毫而莫取。惟江上之清風，與山間之明月，耳得之而為聲，目遇之而成色，取之無禁，用之不竭。是造物者之無盡藏也，而吾與子之所共適。﹄︵共適 壹作：共食︶</p> <p>　　客喜而笑，洗盞更酌。肴核既盡，杯盤狼籍。相與枕藉乎舟中，不知東方之既白。</p>\n";
    public static String str_en = "<p> renxu autumn July, Jiwang, Suzi and guest boating tours under Chibi. Xu breeze, rippleless. Wine is off, chanting the moon poetry, song slim chapter. A little while, months of Dongshan, wandering in the bullfight. Dew Yokoe, Shuiguang next day. Even a reed like, Ling Wan Qing loss. The vast Feng seems such as virtual Yufeng, and not to stop; waving as aloof, emergence and immortal. (Feng Tong) </p> <p>    and drinking music, I and song. The Song said: \"Zhao Gui Xi Lan paddle upstream come blow out light and air. You come to my arms, at beauty come one day.\" A blowing flute, and the Yi song. The hum of course, such as resentment, such as mu of bamboo, linger on faintly, as if weeping and complaining. Dance Youhe the cry of a hidden dragon boat. </p> <p> Suzi stern, sat, and asked the guests said: \"what is it?\" The guests said: \"yuemingxingxi, Ukraine magpie flying south.\" This is not a poem of Cao Mengde? Seomang Xiakou, looking east Wuchang mountains, Miao Yu, between green and the non shuro Meng moral trapped in between? The broken Jingzhou, Jiangling, East River, a convoy of ships thousands of miles, empty word flags, pour wine, having a lance sideward and poetizing Linjiang, a hero of the age and where is also solid,? Kuangwu and son, in Jiang Nagisa, Lu fish and shrimp and the friends of the elk, riding a leaf boat, belonging to lift bottle gourd. Send ephemera in the world, a boundless sea. Sad moment of my life, the infinite envy of Yangtze river. With the fly to roam, hold the moon and long end. Don't know will suddenly left, supporting ring in Beifeng.\" </p>";
    public static String str_muti = "<p>　　壬戌之秋，renxu autumn July, 七月既望，Jiwang, 苏子与客泛舟游于赤壁之下。Suzi and guest boating tours under Chibi.清风徐来，水波不兴。 Xu breeze, rippleless. 举酒属客，Wine is off, 诵明月之诗，chanting the moon poetry, 歌窈窕之章。song slim chapter. 少焉，A little while, 月出于东山之上，months of Dongshan, 徘徊于斗牛之间。wandering in the bullfight. 白露横江，Dew Yokoe, 水光接天。Shuiguang next day. 纵一苇之所如，Even a reed like, 凌万顷之茫然。Ling Wan Qing loss. 浩浩乎如冯虚御风，The vast Feng seems such as virtual Yufeng, 而不知其所止；and not to stop; 飘飘乎如遗世独立,waving as aloof, 羽化而登仙。emergence and immortal. (冯 通：凭)(Feng Tong)</p> <p>　　于是饮酒乐甚，then drinking music very, 扣舷而歌之。 I and song. 歌曰：“桂棹兮兰桨，击空明兮溯流光。渺渺兮予怀，望美人兮天一方。”。The Song said: \"Zhao Gui Xi Lan paddle upstream come blow out light and air. You come to my arms, at beauty come one day.\"。客有吹洞箫者，A blowing flute, 倚歌而和之。 and the Yi song. 其声呜呜然，The hum of course, 如怨如慕，such as resentment, 如泣如诉；such as mu of bamboo, 余音袅袅，linger on faintly, 不绝如缕。as if weeping and complaining. 舞幽壑之潜蛟，泣孤舟之嫠妇。Dance Youhe the cry of a hidden dragon boat.</p>";
    public static String str_hhl = "登黄鹤楼\n昔人已乘黄鹤去\n此地空余黄鹤楼\n黄鹤一去不复返\n白云千载空悠悠\n晴川历历汉阳树\n芳草萋萋鹦鹉洲\n日暮乡关何处是\n烟波江上使人愁";
    public static String str_juaner = "采采卷耳，不盈頃筐。\n嗟我懷人，寘彼周行。\n︵寘 通：置︶\n陟彼崔嵬，我馬虺隤。\n我姑酌彼金罍，\n維以不永懷。\n陟彼高岡，我馬玄黃。\n我姑酌彼兕觥，\n維以不永傷。\n陟彼砠矣，我馬瘏矣，\n我仆痡矣，雲何籲矣。";
}
